//
// Created by jh on 11/8/23.
//

#ifndef KVSPRODUCERSERVICE_KVSSERVICEPROXY_H
#define KVSPRODUCERSERVICE_KVSSERVICEPROXY_H

class KvsServiceProxy {};

#endif // KVSPRODUCERSERVICE_KVSSERVICEPROXY_H
