#ifndef FXN_MIDDLEWARE_RESULTTYPE_H
#define FXN_MIDDLEWARE_RESULTTYPE_H

enum class ResultType {
    OK = 0,
    ERROR = 100,
    ERROR_BUSY = 101,
    ERROR_INVALID_JSON_FORMAT = 102,
    ERROR_INVALID_INPUT = 103,
    ERROR_OUT_OF_RANGE = 104,
    UKnown = 999999
};

#endif //FXN_MIDDLEWARE_RESULTTYPE_H
